### ISSUE TITLE
Integrate Openstreetmap

### ISSUE THREAD

**Issue by mtbitcr** [BitcreditProtocol/E-Bill-frontend#110]
We want to add integration with OpenStreetMap to select addresses when creating personal as well as company profiles. This should be a component that will be used in many places. We also need to see what format the API returns the address in. We need to break it down into a JSON object with each individual field anyway.

**Comment by mjkeaton** [comment]
[Closed for now](https://github.com/BitcreditProtocol/E-Bill-frontend/pull/113#issuecomment-2520000303). Reopen at will.
