### ISSUE TITLE
Bills > Green color is not correct

### ISSUE THREAD

**Issue by mtbitcr** [BitcreditProtocol/E-Bill-frontend#42]

**Comment by mjkeaton** [comment]
This seems to have been alread done in 566524f70f2e209b585673649d2979d4c41375a9.
Success color[ changed to #006F29](https://github.com/BitcreditProtocol/E-Bill-frontend/commit/566524f70f2e209b585673649d2979d4c41375a9#diff-ddc1067f080930bc48865f4660316a14b21bbc9f9ba85975ce8479342b983d2eR80).

<img src="https://github.com/user-attachments/assets/9fd360e6-d22c-4884-a716-923f8e135cc4" width=250 />

Please reopen if you think this is a mistake.
