### ISSUE TITLE
Create discount calculation component

### ISSUE THREAD

**Issue by mtbitcr** [BitcreditProtocol/E-Bill-frontend#45]
Create discount calculation component:

When issuing a bill, the user can also set a discount rate to be applied to the bill.
Fields for the component:
[ ] date range: simple dropdown with dates range options: 30, 60, 90, 120, 150, 180 days; required
[ ] discount rate: numeric field; required
[ ] net amount: currency field; required. Taken from issue currency

The component must also display the final calculation of the amount:
- mark up: currency formatted value
- gross amount: currency formatted value

After filling the calculation fields, the final value is updated on the "bill value" field on the issue bill form.

**Comment by Harsha-Vardhan-24** [comment]
Hi @mtbitcr, Can you explain more about this issue looks this to implement this I also need to access the backend and database I think so... If you can explain more about this problem I am happy to help.

**Comment by mtbitcr** [comment]
Hey, @Harsha-Vardhan-24. Thank you for your willingness to help.

To implement this task, you don't need access to either the database or the backend. 

We need to implement a component that can be used multiple times (at the time of signing the bill of exchange, at the time of selling the bill of exchange and at the time of minting the bill of exchange). Therefore, it should be a separate, importable component.
Its idea is to calculate the recommended value of a bill of exchange. It will be based on a mathematical formula. At the moment it will be the same for all countries, this will change in the future. Therefore the component must be implemented through an interface and abstraction.

Here's the formula: **(t1-t0)/365*e^i**
**t1** is maturity
**t0** is now
**i** is annual discount rate

Component view. The style should be adaptive for both mobile devices and desktops. There will be a dark theme soon. Keep that in mind:
![Screenshot 2024-11-13 at 10 20 38](https://github.com/user-attachments/assets/e39a1509-f507-4a23-91fe-1b27f71cfaf0)

@cryptosalomao will help you with technical as well as style details.

**Comment by cryptosalomao** [comment]
Hello @Harsha-Vardhan-24, thanks for expressing you interest in helping us with this task!

To get started, please take a look on the Figma design specs. There you can find all the necessary references to move forward with your contribution:

https://www.figma.com/design/XqVOGOoS8tZhGK5ROmqGFv/Open-tasks?node-id=1-548&node-type=section&t=fgUoYQvm8bIh3H1g-0

We have two variants of this component, that are used in two different places, so a minimal abstraction for the two different styles is recommended.

Also notice that we are using variables for our color styles, so please stick with the conventions when working on the component. You may refer to [this file](https://github.com/BitcreditProtocol/E-Bill-frontend/blob/main/tailwind.config.js) to check how we've named the color variables, and make use of them.

If you need any help, please reach out! I'll be happy to help.

**Comment by HubertusVIE** [comment]
I need to be more explicit, here is the formula: gross_amount = (t1-t0)/365*e^i * net_amount

We sometimes have to calculate gross (issue), sometimes net (sell, ...). But we must also be able to switch.

**Comment by cryptosalomao** [comment]
Hey @Harsha-Vardhan-24 did you have a chance to get started on this one?

**Comment by Harsha-Vardhan-24** [comment]
Hi @cryptosalomao, I have made some progress almost completed the 1st design in the Figma file, I got some other work to do so I couldn't complete this one will most probably complete it by today or tomorrow, But I am having few doubt is it possible to connect to you guys via discord or any other platform? 

![image](https://github.com/user-attachments/assets/ee81e0f2-4436-4ac1-b0a0-b3372cc53253)

**Comment by mtbitcr** [comment]
@Harsha-Vardhan-24 I have added your in our Discord Developers chat. But we mostly communicated here or in TG.

**Comment by mtbitcr** [comment]
Hello @Harsha-Vardhan-24. You're still working on that task. Or should we put it back on TO DO and open it up to everyone?

**Comment by Harsha-Vardhan-24** [comment]
Hi @mtbitcr, I am currently out of station, So I cannot work on this issue now, I will be back on 30th of November, Then I can start working on the points mentioned, Thank you...!

**Comment by mjkeaton** [comment]
Can we get detailed test vectors for this? @mtbitcr @HubertusVIE

**Comment by HubertusVIE** [comment]
Calculations and future warnings here:
https://docs.google.com/spreadsheets/d/1YGI32u4QEVDLD8SksdvDjaQ4z3WjL1GrIHgVUxNaQqI/edit?gid=0#gid=0
