### ISSUE TITLE
Update checkbox component

### ISSUE THREAD

**Issue by cryptosalomao** [BitcreditProtocol/E-Bill-frontend#50]
The checkbox component has a new design, therefore we must update the existing checkbox component file to match the design specifications.

### Design reference
The design specifications for the new design can be found on the following Figma link:
https://www.figma.com/design/XqVOGOoS8tZhGK5ROmqGFv/Open-tasks?node-id=41-73&node-type=section&t=HnHWrabcCxphoBCO-0

### Development
We use shadcn as base for our components implementation, and tailwind for styling. Please stick to both libraries conventions. Make use of class utilities to style the component. For example: set width and height with `w-4 h-4` for the small size and `w-5 h-5` for the medium size.

The existing checkbox component file is located at:
https://github.com/BitcreditProtocol/E-Bill-frontend/blob/revamp/src/components/ui/checkbox.tsx

As a reference on how to implement the variations, please check the following component:
https://github.com/BitcreditProtocol/E-Bill-frontend/blob/revamp/src/components/ui/button.tsx#L10

It's also important to follow the brand guidelines for the colors. The Figma specs already use the naming conventions, and they can be found on the code base at the tailwind configuration file:
https://github.com/BitcreditProtocol/E-Bill-frontend/blob/revamp/tailwind.config.js#L85

### Acceptance criteria:

- [ ] The component styling must match all the states specified in the design specs: default, hover and disabled
- [ ] The component must have two different sizes, as per the design specs: small (sm) and medium (md)
- [ ] There has to be a property to set the checkbox state (checked or unchecked)
- [ ] There has to be a property to set the checkbox size (sm or md)
- [ ] There has to be a property to turn the checkbox into the disabled state

## Important: branch from revamp

**Comment by cryptosalomao** [comment]
Hey @matosGu1lherme take a look at this issue. It's a very simple yet very important task that is a good start for new contributors. Please let me know if you need any help to move forward with it!

**Comment by matosGu1lherme** [comment]
Hi, @cryptosalomao , I found this issue very interesting, could you assign it to me?

**Comment by mjkeaton** [comment]
Can be closed once `revamp` finds its way into `main`.
