### ISSUE TITLE
Primary button variant

### ISSUE THREAD

**Issue by cryptosalomao** [BitcreditProtocol/E-Bill-frontend#51]
The button component has a new design for its primary variant, therefore we must update the existing component to match the design specifications.

### Design reference
The design specifications for the new design can be found on the following Figma link:
https://www.figma.com/design/XqVOGOoS8tZhGK5ROmqGFv/Open-tasks?node-id=41-2228&node-type=frame&t=HnHWrabcCxphoBCO-0

### Development
We use shadcn as base for our components implementation, and tailwind for styling. Please stick to both libraries conventions. Make use of class utilities to style the component.
Since shadcn already provides us with a base button component, some variations from the Figma reference are not necessary to be implemented, such as the icon button variant.

The existing component can be found on:
https://github.com/BitcreditProtocol/E-Bill-frontend/blob/revamp/src/components/ui/button.tsx

Please notice that the current Figma file only has the primary button variant. The other variants will be added later on, but the component must be prepared to receive it.

It's also important to follow the brand guidelines for the colors. The Figma specs already use the naming conventions, and they can be found on the code base at the tailwind configuration file:
https://github.com/BitcreditProtocol/E-Bill-frontend/blob/revamp/tailwind.config.js#L60

Pay special attention to the width and height, border radiuses and padding variations, as they are different for each size.

### Acceptance criteria:
- [ ] The component styling must match all the states specified in the design specs: default, hover, focused, active and disabled
- [ ] The component must have two different sizes, as per the design specs: extra small (xs), small (sm), medium (md) and large (lg)
- [ ] There has to be a property to set the button size (xs, sm, md or lg)
- [ ] There has to be a property to turn the button into the disabled state
- [ ] The component must have a full width variant
- [ ] The component must have a full rounded variant

## Important: branch from revamp

**Comment by nafisreza** [comment]
Could you please explain the difference between left and left justified?
<img width="458" alt="image" src="https://github.com/user-attachments/assets/93a59719-26e8-44e7-bfc7-477f899746b6">

**Comment by mtbitcr** [comment]
@nafisreza Thank you for your contribution! You will be rewarded with 500 tokens at the beginning of the next quarter.
