### ISSUE TITLE
Search component

### ISSUE THREAD

**Issue by cryptosalomao** [BitcreditProtocol/E-Bill-frontend#75]
### Search component

The search field component is going to be used more than once throughout the application. It is a simple component that consists of a text field and a search icon.

#### Design reference

The current specifications for this component can be found in the following link:
https://www.figma.com/design/XqVOGOoS8tZhGK5ROmqGFv/Open-tasks?node-id=131-3164&node-type=frame&t=ylJesJp7IAC7tzGk-0

#### Development

There is no need for flexibility in terms of customization for the layout, and the icon used is standard. The text field is used to input the search query, and by hitting enter, the action to search must be triggered. It's also important to note that the search field must be able to receive a callback function to handle the action result, and a placeholder text.

The variations for the component are all related to the size, that have custom icon sizes, font size and container height. The size variants are: `xs`, `sm`, `md` and `lg`.

It's important to pay attention to the 3 different states of the component: `default`, `hover` and `focus`. It's not necessary to have a `disabled` state for this component.

Even though the component is an input, it's structurally different than the `<Input />` component that we currently have, therefore, it's necessary to create a new one from scratch.

There is a version of this component available in this pull request and it can be used as a basis for the creation of the new one:
https://github.com/BitcreditProtocol/E-Bill-frontend/blob/c7aff91a7f01b705b96673f6a937fa23b62bee25/src/pages/contacts/Overview.tsx#L7

### Acceptance criteria

- [ ] The component must be able to receive a callback function to handle the search action
- [ ] The component must be able to receive a placeholder text
- [ ] The component must have 4 size variants: `xs`, `sm`, `md` and `lg`
- [ ] The component must have 3 states: `default`, `hover` and `focus`
- [ ] The component must be documented with stories in Storybook

## Important: branch from `main`

**Comment by mtbitcr** [comment]
@nafisreza Thank you for your contribution! You will be rewarded with 500 tokens at the beginning of the next quarter.
