### ISSUE TITLE
Input component

### ISSUE THREAD

**Issue by cryptosalomao** [BitcreditProtocol/E-Bill-frontend#76]
### Input component

We have now the complete design specifications for our input component. Under the hood, we use the component provided by shadcn, with custom functionalities to achieve the envisioned behavior.

#### Design reference
The design specifications for the component and its variants can be found in the following link:
https://www.figma.com/design/XqVOGOoS8tZhGK5ROmqGFv/Open-tasks?node-id=131-746&node-type=frame&m=dev

#### Development
The existing component code can be found in the following link:
https://github.com/BitcreditProtocol/E-Bill-frontend/blob/main/src/components/ui/input.tsx

It already has the basic structure and style in the current state, and the click behavior is already implemented too, that is: when the user clicks on the input, the label must move up and the input element is focused. The `required` property is already implemented and works as intended too.

There are some missing functionalities that need to be implemented: custom icon property, clear field button, and a hint component below the field that will serve either as a feedback or as an error/warning message for the user.

The size variants that have to be implemented are: `sm`, `md` and `lg`. Please notice the different values for the font size, icon size, padding and gap between each size variant.

The states variantes are: `typing`, `default`, `hover`, `disabled`, `filled`, `success` and `error`. There are subtle differences in some of the variants, so please pay attention to those details.

For the icon, it will be placed only at the left side of the field, when present. There has to be a property to define if the field is `clearable` and then it must show the clear button on the right side of the field.

The library we're using for the forms handling is `react-hook-form`, so the component must be compatible with it in each state triggered by the library, like validation errors and so on.

Please read the API documentation for the `react-hook-form` library to understand how to handle the form states and how to integrate the input component with it in the following link:
https://react-hook-form.com/docs/useform

#### Acceptance criteria

- [ ] The component must have the size variants `sm`, `md` and `lg`.
- [ ] The component must have the states variants `typing`, `default`, `hover`, `disabled`, `filled`, `success` and `error`.
- [ ] The component must have a property to define if it is `clearable` or not.
- [ ] The component must have a property to define the icon to be displayed.
- [ ] The component must have a hint component below the field that will serve either as a feedback or as an error/warning message for the user.
- [ ] The component must be compatible with the `react-hook-form` library.
- [ ] The component must be documented with stories using Storybook.

## Important: branch from `main`

**Comment by nafisreza** [comment]
will work on this next

**Comment by nafisreza** [comment]
@cryptosalomao kindly check your discord dm

**Comment by mtbitcr** [comment]
@nafisreza. Thank you for your contribution! You will be rewarded with 500 tokens at the beginning of the next quarter.
